# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='cp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='facture',
            name='quantite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.IntegerField(null=True),
        ),
    ]
