# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_facture_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
