# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_auto_20160304_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
