# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_auto_20160304_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_created']},
        ),
    ]
