# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factures', '0006_auto_20160307_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('paid', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('credit_job', models.IntegerField(default=0)),
                ('credit_cv', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
