# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0007_paymentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='link',
            field=models.CharField(blank=True, help_text='http://pitchmyjob.com/pro/paiement/[link]', max_length=250, null=True),
        ),
    ]
