# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_auto_20160325_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlink',
            old_name='prix_ttc',
            new_name='prix_ht',
        ),
    ]
