# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_objet_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='objet',
        ),
        migrations.AddField(
            model_name='contact',
            name='objets',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Objet',
        ),
    ]
