# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160119_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=150, null=True)),
                ('titre', models.CharField(max_length=150, null=True)),
                ('nom', models.CharField(max_length=150, null=True)),
                ('prenom', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('formation', models.CharField(max_length=150, null=True)),
                ('experience', models.CharField(max_length=150, null=True)),
                ('ville', models.CharField(max_length=150, null=True)),
                ('birthday', models.DateField(null=True)),
            ],
        ),
    ]
