# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_apec_dispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apec',
            name='publication',
            field=models.DateField(null=True),
        ),
    ]
