# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20160419_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='apec',
            name='vague',
            field=models.IntegerField(null=True),
        ),
    ]
