# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
