# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('poste', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='CvExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='c2v/logo/')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2v.Cv')),
            ],
        ),
        migrations.CreateModel(
            name='CvFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200, null=True)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('degree', models.CharField(max_length=200, null=True)),
                ('discipline', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='c2v/logo/')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2v.Cv')),
            ],
        ),
        migrations.CreateModel(
            name='CvInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2v.Cv')),
            ],
        ),
        migrations.CreateModel(
            name='CvLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('level', models.IntegerField(null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2v.Cv')),
            ],
        ),
        migrations.CreateModel(
            name='CvSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('level', models.IntegerField(null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2v.Cv')),
            ],
        ),
    ]
