# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2v', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='theme',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
