# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2v', '0002_cv_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvexperience',
            options={'ordering': ['-date_start', '-date_end']},
        ),
        migrations.AlterModelOptions(
            name='cvformation',
            options={'ordering': ['-date_start', '-date_end']},
        ),
    ]
