# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2v', '0003_auto_20160128_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='age',
        ),
        migrations.AddField(
            model_name='cv',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
