# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 16:57
from __future__ import unicode_literals

import c2v.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('c2v', '0006_auto_20160419_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvexperience',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=c2v.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='cvformation',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=c2v.models.generate_filename),
        ),
    ]
