"""
Django settings for myc2v project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import raven
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd5_ma$k8%8lul5#bzj-3u%h!8p7av@_cn$z0hdfv%v+&^t*n+^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

LOGIN_URL = '/login'
LOGIN_URL_PRO = '/pro/login'
REDIRECT_URL_PRO = '/pro'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'xhtml2pdf': {
            'handlers': ['console'],
            'level': 'DEBUG'
       },
   }
}


THUMBNAIL_ALIASES = {
    '': {
        'logo100': {'size': (100, 0), 'crop': "smart"},
        'logo50': {'size': (50, 0), 'crop': "smart"},
        'cover940': {'size': (940, 200), 'crop': "smart"},
        'cover840': {'size': (890, 200), 'crop': "smart"},
        'cover280': {'size': (290, 80), 'crop': "smart"},
        'profil100': {'size': (100, 100), 'crop': "smart"},
        'profil50': {'size': (50, 50), 'crop': "smart"},
        'fb': {'size': (600, 350), 'crop': False},
    },
}


# Application definition 

INSTALLED_APPS = [
    'raven.contrib.django.raven_compat',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps', 
    'rest_framework',
    'rest_framework.authtoken',
    'pure_pagination',
    'easy_thumbnails', 
    'widget_tweaks',
    'pages',
    'api',
    'members',
    'pro', 
    'c2v',
    'notifications',
    'factures',
    'storages'
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myc2v.middlewares.SetLastVisitMiddleware',
    'myc2v.middlewares.MobileDetectionMiddleware',
]

ROOT_URLCONF = 'myc2v.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates/")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myc2v.context_processors.token_api',
                'myc2v.context_processors.nb_msg'
            ],
        },
    },
]

WSGI_APPLICATION = 'myc2v.wsgi.application'


YOUTUBE_AUTH_EMAIL = 'myc2v.api@gmail.com'
YOUTUBE_AUTH_PASSWORD = 'cvG456hz'
YOUTUBE_DEVELOPER_KEY = 'AIzaSyB9XJwjGTdtnDfUL7R4Wwz-e6F8BIiaJdg'
YOUTUBE_CLIENT_ID = 'AIzaSyB9XJwjGTdtnDfUL7R4Wwz-e6F8BIiaJdg'

YOUTUBE_UPLOAD_REDIRECT_URL = '/youtube/videos/'
YOUTUBE_DELETE_REDIRECT_URL = '/myurl/'


PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 5,
    'MARGIN_PAGES_DISPLAYED': 1,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

DAYS_JOB = 40





#AWS STORAGE ------------------------------

AWS_STORAGE_BUCKET_NAME = 'v1-pitchmyjob'
AWS_ACCESS_KEY_ID = 'AKIAJ3277WDQOUGCUUTQ'
AWS_SECRET_ACCESS_KEY = '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'

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

STATICFILES_LOCATION = 'static'
STATICFILES_STORAGE = 'myc2v.custom_storages.StaticStorage'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)

MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'myc2v.custom_storages.MediaStorage'


THUMBNAIL_DEFAULT_STORAGE = 'myc2v.custom_storages.MediaStorage'

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static"),
#    '/var/www/static/',
#]
# -----------------------------------




# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases


#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_HOST_USER = 'myc2v.api@gmail.com'
#EMAIL_HOST_PASSWORD = 'cvG456hz'
#EMAIL_PORT = 587
EMAIL_USE_TLS = True


#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'localhost'
#EMAIL_PORT = 25
#EMAIL_HOST_USER = ''
#EMAIL_HOST_PASSWORD = ''
#EMAIL_USE_TLS = False
#DEFAULT_FROM_EMAIL = 'Pitchmyjob <No-reply@ptichmyjob.com>'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'in-v3.mailjet.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '716554e44256731439609ad75c0c64eb'
EMAIL_HOST_PASSWORD = '4fe406245518835c398c0e8bf8f74209'
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'Pitchmyjob <No-reply@ptichmyjob.com>'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pitchmyjob',
        'USER': 'pitch',
        'PASSWORD': 'cvG456hz',
        'HOST': 'production-v1-rds.cw2dxsgsldpl.eu-west-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


#DATABASES_no = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'myc2v',
#        'USER': 'myc2v_u',
#        'PASSWORD': 'Gf46mvv',
#        'HOST': 'localhost',
#        'PORT': '',
#    }
#}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    )
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'fr'

DEFAULT_LANGUAGE = 1

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
  ('fr', _('French')),
  ('en', _('English')) 
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/



DECIMAL_SEPARATOR = '.'

WEB_URL = "https://www.pitchmyjob.com"

# CELERY STUFF
BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_IMPORTS=("notifications.notifications", )

RAVEN_CONFIG = { 'dsn': 'https://6c7f06463e1b4ce5af60f8040f8f506c:7d9958068dc942808a16f8e7b8574c96@app.getsentry.com/67699',}



