# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myc2v.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exp\xe9rience',
                'verbose_name_plural': 'Liste exp\xe9rience',
            },
            bases=(myc2v.mixins.UnicodeNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField(null=True)),
                ('job_wanted', models.CharField(max_length=150, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('availability', models.DateField(blank=True, null=True)),
                ('search_location', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Niveau d'\xe9tude",
                'verbose_name_plural': "Liste niveau d'\xe9tude",
            },
            bases=(myc2v.mixins.UnicodeNameMixin, models.Model),
        ),
        migrations.AddField(
            model_name='member',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Study'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
