# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20151212_0223'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activity_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro.ActivityArea'),
        ),
        migrations.AddField(
            model_name='member',
            name='contracts',
            field=models.ManyToManyField(blank=True, to='pro.Contract'),
        ),
    ]
