# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 03:30
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20151212_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='c2v/mycv_default.png', upload_to=members.models.generate_filename),
        ),
    ]
