# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=250, null=True)),
                ('type_video', models.IntegerField(null=True)),
                ('embed_url', models.CharField(max_length=250, null=True)),
                ('link_url', models.CharField(max_length=250, null=True)),
                ('file_on_server', models.FileField(null=True, upload_to='videos')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
