# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20151216_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type_video',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
