# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_auto_20151217_0445'),
        ('members', '0009_auto_20151217_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(blank=True, default=0)),
                ('active', models.BooleanField(default=False)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro.Job')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatureReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.IntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('candidature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Candidature')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Video')),
            ],
        ),
    ]
