# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20151218_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidaturereponse',
            options={'ordering': ['nb']},
        ),
        migrations.AddField(
            model_name='member',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
