# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20151224_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturereponse',
            name='audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature', to='members.Audio'),
        ),
    ]
