# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_candidaturereponse_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='token_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
