# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_token_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rs_pwd',
            field=models.BooleanField(default=False),
        ),
    ]
