# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_member_rs_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
