# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20160105_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['ordre'], 'verbose_name': 'Exp\xe9rience', 'verbose_name_plural': 'Liste exp\xe9rience'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['ordre'], 'verbose_name': "Niveau d'\xe9tude", 'verbose_name_plural': "Liste niveau d'\xe9tude"},
        ),
    ]
