# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20160106_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='decline',
            field=models.BooleanField(default=False),
        ),
    ]
