# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_candidaturereponse_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature', to='members.Video'),
        ),
        migrations.AlterField(
            model_name='candidaturereponse',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_reponse', to='members.Video'),
        ),
    ]
