# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20160110_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature', to='members.Audio'),
        ),
        migrations.AlterField(
            model_name='candidaturereponse',
            name='audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_reponse', to='members.Audio'),
        ),
    ]
