# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20160119_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
