# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_candidature_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/%Y/%m/', validators=[members.models.validate_file_extension]),
        ),
    ]
