# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_auto_20160128_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='activity_area',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=members.models.candidature_file, validators=[members.models.validate_file_extension]),
        ),
    ]
