# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0020_auto_20160208_1853'),
        ('members', '0028_auto_20160208_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activity_area',
            field=models.ManyToManyField(blank=True, to='pro.ActivityArea'),
        ),
    ]
