# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_member_activity_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, help_text="lien d'acces a la video : http://pitchmyjob.com/media/records/[video_id].mp4", max_length=250, null=True),
        ),
    ]
