# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0027_auto_20160319_1715'),
        ('members', '0031_auto_20160307_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pro.Tag'),
        ),
    ]
