# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_member_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
