# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 15:13
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='c2v/mycv_default.png', upload_to=members.models.generate_filename),
        ),
    ]
