# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_auto_20160412_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rs_doyoubuzz_cv',
            field=models.FileField(blank=True, null=True, upload_to='doyoubuzz/'),
        ),
        migrations.AddField(
            model_name='member',
            name='rs_type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
