# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Interet', 'verbose_name_plural': 'Liste des interess\xe9s'},
        ),
    ]
