# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_video_aws'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cv_pdf',
            field=models.FileField(null=True, upload_to=members.models.generate_filename),
        ),
    ]
