# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_auto_20160819_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
