# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0043_pro_active'),
        ('members', '0041_auto_20160909_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro.Job'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, help_text='https://s3.eu-central-1.amazonaws.com/pitchmyjob/[video_id].mp4', max_length=250, null=True),
        ),
    ]
