# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_auto_20160909_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='member',
        ),
    ]
