# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_remove_video_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
