# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_video_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
