# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_member_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-date'], 'verbose_name': 'Interet', 'verbose_name_plural': 'Liste des interess\xe9s'},
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
