# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20160110_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
