# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
