# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
