# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experiences',
            field=models.ManyToManyField(to='members.Experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='studies',
            field=models.ManyToManyField(to='members.Study'),
        ),
    ]
