# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20151212_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Pro'),
        ),
    ]
