# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_auto_20151217_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='link_facebook',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='link_twitter',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='link_youtube',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
