# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_auto_20151217_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pro',
            name='link_twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pro',
            name='link_youtube',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
