# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_auto_20151217_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestion',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pro.Pro'),
        ),
    ]
