# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_jobquestion_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='administrative_area_level_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='locality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
