# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_auto_20151217_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
