# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0013_auto_20160104_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='street_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
