# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0014_auto_20160104_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_created']},
        ),
    ]
