# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0015_auto_20160106_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
