# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0016_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
