# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0018_auto_20160119_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
