# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0021_auto_20160304_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='credit_job',
            field=models.IntegerField(default=1),
        ),
    ]
