# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0023_auto_20160304_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
