# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0025_auto_20160305_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
