# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0026_job_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scraper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='scraper_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='scraper_site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='scraper_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='scraper',
            field=models.BooleanField(default=False),
        ),
    ]
