# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0032_auto_20160328_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityarea',
            options={'ordering': ['name'], 'verbose_name': "Secteur d'activit\xe9", 'verbose_name_plural': "Liste des secteur d'activit\xe9"},
        ),
        migrations.AddField(
            model_name='activityarea',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
