# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0033_auto_20160328_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityarea',
            options={'ordering': ['-ordre', 'name'], 'verbose_name': "Secteur d'activit\xe9", 'verbose_name_plural': "Liste des secteur d'activit\xe9"},
        ),
    ]
