# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_member_tags'),
        ('pro', '0035_auto_20160329_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=250, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
            options={
                'verbose_name': 'Recherche job',
                'verbose_name_plural': 'Liste des recherches',
            },
        ),
    ]
