# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_member_tags'),
        ('pro', '0036_searchjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seen', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro.Job')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
            options={
                'verbose_name': 'Job consult\xe9',
                'verbose_name_plural': 'Liste job consult\xe9',
            },
        ),
    ]
