# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0038_auto_20160412_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='mp_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mp_multiposting_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mp_multiposting_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mp_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
