# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0043_pro_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mp_flatchr_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
