# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0044_job_mp_flatchr_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='credit_job',
            field=models.IntegerField(default=0),
        ),
    ]
