# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import pro.models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0045_auto_20161111_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=pro.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='pro',
            name='credit_job',
            field=models.IntegerField(default=1),
        ),
    ]
